services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    ports:
      - '8000:8000'
    command: python3 backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app/backend/
      - ./static:/app/static
      - media:/app/media
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=postgres
      - DOCKER=yes
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=db

  frontend:
    build:
      context: ./frontend
    ports:
      - '8080:8080'
    volumes:
      - ./frontend:/app
    command: npm run serve

volumes:
  postgres_data:
  media:
