FROM python:3.12-slim

ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
RUN pip install --upgrade pip setuptools

COPY ./backend/dependencies /dependencies

RUN pip3 install -r dependencies/dev.txt

COPY ./backend /app/backend
COPY pyproject.toml /app/pyproject.toml
RUN adduser django
RUN chown -R django /app

COPY ./compose/django/dev.sh /dev.sh


RUN chmod +x /dev.sh
RUN chmod +x /app/backend/run.sh
WORKDIR /app

ENTRYPOINT ["/dev.sh"]
