name: Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: linters
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: AutoFlake
        run: docker compose run --rm django autoflake --check .
      - name: Flake8
        run: docker compose run --rm django flake8 .
      - name: Black
        run: docker compose run --rm django black . --check
      - name: Isort
        run: docker compose run --rm django isort . --check-only

  backend-tests:
    needs: lint
    name: backend tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Backend Tests with coverage
        run: ./backend/coverage.sh

  backend-validations:
    needs: lint
    name: backend validations
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Backend Validations
        run: ./backend/run.sh check --fail-level WARNING
